---
title       : Die Angst vor dem Relativismus
subtitle    : Paul Feyerabend - Erkenntnis für freie Menschen
author      : Philipp Gadow
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, reveal.js ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---
## Es geht ein Gespenst um in Europa
"Es geht ein Gespenst um in Europa - das Gespenst des Kommunismus. Alle Mächte des alten Europa haben sich zu einer heiligen Hetzjagd gegen dies Gespenst verbündet, der Papst und der Czar, Metternich und Guizot, französische Radikale und deutsche Polizisten.

Wo ist die Oppositionspartei, die nicht von ihren regierenden Gegnern als kommunistisch verschrieen worden wäre, wo die Oppositionspartei, die den fortgeschritteneren Oppositionsleuten sowohl, wie ihren reaktionären Gegnern den brandmarkenden Vorwurf des Kommunismus nicht zurückgeschleudert hätte?

Zweierlei geht aus dieser Thatsache hervor.

Der Kommunismus wird bereits von allen europäischen Mächten als eine Macht anerkannt.

Es ist hohe Zeit dass die Kommunisten ihre Anschauungsweise, ihre Zwecke, ihre Tendenzen vor der ganzen Welt offen darlegen, und den Mährchen vom Gespenst des Kommunismus ein Manifest der Partei selbst entgegenstellen."

(Manifest der Kommunistischen Partei, London 1848)

---
## Gliederung

1. Struktur der Argumentation des Kapitels "Das Gespenst des Relativismus", S.134 - 166
2. Definition von Begriffen
3. Diskussion
4. Angriffspunkte an Feyerabend
5. Einordnung in "Erkenntnis für freie Menschen"
<style>
strong {
  font-weight: bold;
}
</style>

--- .class #id 
## Struktur der Argumentation (1)
### These:
Eine **Tatsache** und die **Einstellung zu dieser Tatsache** sind Grundlagen für die Probleme, die sich hinter der Angst vor dem Relativismus verstecken und dem Angriff auf ihn Substanz verleihen. (S.134)

### Tatsache:
Es gibt in der Welt verschiedene Traditionen.

### Einstellung zur Tatsache: 
Entweder: Neugierde und Übernahme fremder Errungenschaften
(Beispiel: bronzezeitlicher Internationalismus in Ägypten, Mesopotmien, Kleinasien)

Oder: Übertriebene Einschätzung einer Tradition
vergröberte Darstellung der Vorteile einer Tradition hin zu beherrschenden Dichotomien, mit extremer Abwertung der negativen Seite
(Beispiel: 'menschlich - unmenschlich')

--- 
## Struktur der Argumentation (2)
### Klassifikation von Traditionen:

1. opportunistische oder eklektische Traditionen: von Werten geleitet, tolerant, bereit Werte zu verändern oder zu übernehmen
2. dogmatische Traditionen: beharren auf ihren Werten als einziges Maß (S. 136f.)

#### Nebenthese:
polytheistische Traditionen begünstigen den Opportunismus und Eklektizismus, monotheistische den Dogmatismus


|   | Beispiele religiösen Eklektizismus:    | Beispiele dogmatischer Traditionen  | 
|---| -------------------------------------- |-------------------------------------|
|   | Griechische Götterwelt                 | Judentum nach Moses                 |
|   | Religiöse Gesetze des Dschingis Khan   | Rationalistische Traditionen        |
|   | Züge der amerikanischen Geschichte     |   - Xenophanes                      |
|   | Züge der Geschichte der Wissenschaften |   - wissenschaftl. Psychologie      |


---
## Struktur der Argumentation (3)

### Klassifikation von Einstellungen zu Traditionen:

1. opportunistisches Aufnehmen und Verändern von Brauchbarem
2. dogmatisches Beharren auf einer einzigen Tradition mit Hegemonieanspruch
3. der Relativismus (S. 140)

### Erste Definition des Relativismus

> Der Relativismus ist nichts anderes als eine gelehrtere Fassung eines naiven und fruchtbaren Opportunismus.

---
## Eine kurze Geschichte des Relativismus

### Akt 1: Herodot

> "Als Dareios König war, ließ er einmal alle Griechen seiner Umgebung zu sich rufen und fragte sie, um welchen Lohn sie bereit wären, die Leichen ihrer Väter zu verspeisen. Die aber antworteten, sie würden das um keinen Preis tun.
Darauf rief Dareios die indischen Kalatier, die die Leichen ihrer Eltern essen, und fragte sie in Anwesenheit der Griechen ... um welchen Preis sie ihre verstorbenen Väter verbrennen möchten. Sie schrien laut auf und baten ihn inständig, solche gottlosen Worte zu lassen. So steht es mit den Sitten der Völker, und Pindar hat meiner Meinung nach recht, wenn er sagt, die Sitte sei aller Wesen König."

> "Wenn man die Völker der Erde aufforderte, sich unter all den verschiedenen Sitten die trefflichsten auszuwählen, so würde jedes nach genauer Untersuchung doch die eigenen allen anderen vorziehen. So sehr ist jedes Volk davon überzeugt, dass seine Lebensformen die besten sind."

(Herodot 3,38)

---
## Eine kurze Geschichte des Relativismus

### Akt 2: Protagoras

#### Relativismus des Protagoras: 
Gesetze, Sitten, Lebensformen sind zwar relativ, aber sie gelten doch in bestimmten Bereichen.<br>

(sozio-kosmologisch-rechtliche These)


Der Aggregatcharakter charakterisiert die homerische Welt. Es gibt keine allumfassende, einheitliche Erkenntnis oder Wahrheit, sondern nur auf vielfache Weise errungene Kenntnisse. In diese Welt fällt der Relativismus des Protagoras. (S.141ff.)


---
## Eine kurze Geschichte des Relativismus

### Akt 2: Protagoras
"The world of the archaic man is an open world. Its elements are not formed or held together by an underlying substance, they are not appearances from which this substance may be inferred with difficulty. They occasionally coalesce to form assemblages. The relation of a single element to the assemblage to which it belongs is like the relation of a part to an aggregate of parts and not like the relation of a part to an overpowering whole."

"Complete knowledge of an object is complete enumeration of its parts and peculiarities. Humans cannot have complete knowledge.
In case of Homer the world is comprehended as the sum of things, visible in space and not as reason acting intensively."

"Archaic man is a religious eclectic, he does not object to foreign gods and myths, he adds them to the existing furniture of the world without any attempt at synthesis, or a removal of contradictions. There are no priests, there is no dogma, there are no categorical statements about the gods, humans, the world."
(AM, Kapitel 16)

---

## Eine kurze Geschichte des Relativismus

### Erste Gegner: Die Geburt des Rationalismus

Aus Mikroprozessen, die mit Bedeutungswandel von Begriffen hin zum Abstrakten einhergehen, bildet sich der Ursprung des Rationalismus.

Spezifische Begriffe gebrauchte mannigfaltigen Beziehungen werden durch wenige und verallgemeinerte Beziehungen ersetzt. Der Inhalt von Begriffen wird (bewusst) vermindert, um zwingende Beweise zu ermöglichen.

Dieser Gehaltsverlust und ein universell angepasster Wahrheitsbegriff lassen en Irrtum entstehen, dass die neuen Beweise und auf ihnen beruhende Wissenschaften objektiv seien und nicht eine Tradition, der es an konkretem Inhalt fehlt. (S 143f.)

---

## Eine kurze Geschichte des Relativismus

### Ein Gegner: Xenophanes gegen die klassische Götterauffassung:

> "Die Äthiopier bilden ihre Götter schwarz und stumpfnasing, die Thraker bauäugig und rothaarig ... Wenn Kühe, Pferde und Löwen Hände hätten udn damit malen könnten, dann würden die Pferde oferdeähnliche und die Kühe kuhförmige Göttergestalten schaffen ..."

> "Einen Gott gibt es, weder an Gestalt noch an Gedanken den Sterblichen ähnlich. Immer bleibt er an derselben Stelle und ohne Bewegung. Nicht geziemt sichs für ihn, zu wandeln hierhin und dorthin, denn ohne Mühsal lenkt er das All durch die Kraft seines Geistes." (S. 144)

- P: Eine Gottesauffassung, die sich von Volk zu Volk ändert, gilt nirgends.
- P: Die Gottesauffassung ist regional unterschiedlich.
- P: Eine unpersönliche, statische Gottesauffassung gilt überall.
- F: Die Stammesgötter der Griechen, Thraker, etc. sind durch die aufgeklärte Gottesauffassung zu ersetzen.

---

## Struktur der Argumentation (4)

### Gründe für den Relativismus (Opportunismus)
Im Gegensatz zum Dogmatismus ist oftmals eine opportunistische Haltung zu einer Tradition vorteilhafter, kompatibel mit den Grundrechten einer freien Gesellschaft und sachlich nicht mangelhaft. (S. 145)

### These:
Dem Relativismus stehen keine intellektuellen Hindernisse entgegen, jedoch gewaltige emotionale.

---

## Struktur der Argumentation (5)

### Gründe gegen den Relativismus

- starke Identifikation mit den Werten und Geboten der eigenen Tradition
- Indoktrination / Erziehung (emotionale Verhaltensführung)
- Werte der eigenen Tradition sind Lebensgrundlage

"Aber nur wenige Menschen haben die Charakterstärke zuzugeben, dass die Welt, für die sie kämpfen, nicht die ganze Welt ist und dass andere Menschen mit gleichem Recht für radikal andere Lebensformen leiden oder mit Ruhm überhäuft werden." (S.146f.)

---
## Struktur der Argumentation (6)

### Erste Definition des Relativismus

> Der Relativismus ist nichts anderes als eine gelehrtere Fassung eines naiven und fruchtbaren Opportunismus (opportunistisches Aufnehmen und Verändern von Brauchbarem aus Traditionen)

### Präzision der Definition des Relativismus:

1. Der hier besprochene Relativismus bezieht sich auf Traditionen.
2. Traditionen sind für sich betrachtet weder gut noch schlecht, sondern können solche Eigenschaften nur in Relation zu anderen Traditionen erhalten (Sach- und Werturteile sind traditionsabhängig).
3. Traditionen sind nicht gleich wertvoll oder wahr, haben in einer freien Gesellschaft aber gleiche Rechte. (S. 148)

---
## Struktur der Argumentation (7)

### Argumente gegen den Relativismus
1. Relativisten haben keinen Grund Gesetze zu achten, Versprechungen einzuhalten oder dem Leben anderer einen Wert zuzuschreiben. Darum sind sie wie wilde Bestien und eine Gefahr für zivilisiertes Leben.
2. Der Relativismus will alle (unnützen) ideologischen Bestandteile der rationalistischen Ordnung entfernen, was nicht ohne Abstieg ins Chaos geschehen kann.

P: Der Relativismus lässt dem Individuum freie Hand.
P: Drohendes Chaos kann durch Ideen wie Wahrheit oder Menschlichkeit gebändigt werden.
P: Durch unbeschränkte Handlungsmöglichkeiten ist der Relativist nicht an Ideen gebunden.
F: Der Relativismus sorgt für ein drohendes Chaos.

---
## Struktur der Argumentation (7)

### Argumente gegen den Relativismus
1. Relativisten haben keinen Grund Gesetze zu achten, Versprechungen einzuhalten oder dem Leben anderer einen Wert zuzuschreiben. Darum sind sie wie wilde Bestien und eine Gefahr für zivilisiertes Leben.
2. Der Relativismus will alle (unnützen) ideologischen Bestandteile der rationalistischen Ordnung entfernen, was nicht ohne Abstieg ins Chaos geschehen kann.
3. Man darf Menschen nicht schutzlos dem Einfluss barbarischer Traditionen überlassen.
(Nebenschauplatz Medizinkritik) (S.149 - 156)

---
## Struktur der Argumentation (8)

### Handlungsoptionen des Einzelnen
Entfremdung und Professionalisiserung der Philosophen von der Bevölkerung erschwert die Berücksichtigung anderer Menschen

praktische Analyse als Gegenmodell zur Kritischen Analyse

<!--
## Anmerkung zum Verweis auf AM Kapitel 17

To sum up: the archaic world is much less compact than the world that surrounds us, and it is also experienced as being less compact. Archaic man lacks physical unity, his body consists of a multitude of parts, limbs, surfaces, connections; and his mind is composed of a variety of events, some of them not even mental in our sense, which either inhabit the body-puppet as additional constituents or are brought into it from the outside.

Events are not shaped by the individual, they are complex arrangements of parts into which the body-puppet is inserted at the appropriate place. This is the world-view that emerges from an analysis of the formal features of archaic art and Homeric poetry, taken in conjunction with an analysis of the concepts which the Homeric poet used for describing what he perceives. Its main features are experienced by the individuals using the concepts. These individuals live indeed in the same kind of world that is constructed by their artists.

For the lack of compactness just described reappears in the field of ideology. There is a tolerance in religious matters which later generations found morally and theoretically unacceptable and which even today is regarded as a manifestation of frivolous and simple minds.
Archaic man is a religious eclectic, he does not object to foreign gods and myths, he adds them to the existing furniture of the world without any attempt at synthesis, or a removal of contradictions. There are no priests, there is no dogma, there are no categorical statements about the gods, humans, the world. (This tolerance can still be found with the Ionian philosophers of nature who develop their ideas side by side with myth without trying to eliminate the latter.) There is no religious morality in our sense, nor are the gods abstranct embodiments of eternal principles. This they became later, during the archaic age, and as a result they lost their humanity. Hence Olympianism in its moralized form tended to become a religion of fear, a tendency which is reflected in the religious vocabulary. There is no word for god-fearing in the Iliad. This is how life was dehumanized by what some people are pleased to call moral progress or scientific progress.

Similar remarks apply to the theory of knowledge that is implicit in this early world-view. The Muses in Iliad 2.284ff, have knowledge because they are close to things - they do not have to rely on rumours - and because they know all the many things that are of interest to the writer, one after the other. Quantity, not intensity is Homer's standard of judgement and of knowledge, as becomes clear from such words as much pondering and much thinking as well as from later criticisms such as Lerning of many things does not teach intelligence. An interest in, and a wish to understand, many amazing things (such as earthquakes, eclipses of the sund and the moon, the paradoxical rising and falling of the Nile), each of them explained in its own particular way and without the use of universal principles, persists in the coastal descriptions of the 8th and 7th (and later) centuries (which simply enumerate the tribes, tribal habits, and coastal formations that are successively met during the journey), and even a thinker such as Thales is satisfied with making many interesting observations and providing many explanations without trying to tie them together in a system. (The first thinker toi construct a system was Anaximander, who followed Hesiod.)
Knowledge so conceived is not obtained by trying to grasp an essence behind the reports of the senses but buy (1) putting the observer in the right position relative to the object (process, aggregate), by insterting him into the appropriate place in the complex pattern that constitutes the world, and (2) by adding up the elements which are noted under these circumstances. It is the result of a complex survey carried out from suitable vantage points. 

Nor is there any uniform conception of knowledge. A great variety of words is used for expressing what we today regard as different forms of knowledge, or as different ways of acquiring knowledge. Sophia means expertise in a certain profession (carpenter, singer, general, physician, charioteer, wrestler) including the arts (where it praises the artist not as an outstanding creator but as a master of his craft); edenai, literally having seen, refers to knowledge gained from inspection; suniemi, especially in the Iliad, though often translated as listening or understanding is stronger - it contains the idea of following and obeying, one absorbs something and acts in accordance with it (hearing may play an important role). And so on. 

[The world of the archaic man is an open world. Its elements are not formed or held together by an underlying substance, they are not appearances from which this substance may be inferred with difficulty. They occasionally coalesce to form assemblages. The relation of a single element to the assemblage to which it belongs is like the relation of a part to an aggregate of parts and not like the relation of a part to an overpowering whole. The particualr aggregate called man is visited and occasionally inhabited by mental events. Such events may reside in him, they may also enter from the outside. Like every other object man is an exchange station of influences rather than a unique source of action an I (Descartes' cogitp has no point of attack in this world, and his argument cannot even start). 

Complete knowledge of an object is complete enumeration of its parts and peculiarities. Humans cannot have complete knowledge.
In case of Homer the world is comprehended as the sum of things, visible in space and not as reason acting intensively.

## Zehn Thesen aus Agains Method Kapitel 18

1. Traditions are neither good nor bad, they simply are.
2. A tradition assumes desirable or undesirable properties only when compared to some tradition.
3. The first two points imply a relativism of precisely the kind that seems to have been defended by Protagoras
4. Every tradition has special ways of gaining followers.
5. Judging a historical process one may use an as yet unspecified and unspecifiable practice.
6. There are at least two different ways of collectively deciding an issue (guided exchange, open exchange)
7. A free society is a society in which all traditions are given equal rights, equal access to education and other positions of power.
8. A free society will not be imposed but will emerge only where people engaging in an open exchange introduce protective structures of the kind alluded to.
9. The debates settling the structure of a free society are open debates not guided debates.
10. A free society insists on the separation of science and society.
-->
